// This file was automatically generated by lister-gen

package v1

// CassandraClusterListerExpansion allows custom methods to be added to
// CassandraClusterLister.
type CassandraClusterListerExpansion interface{}

// CassandraClusterNamespaceListerExpansion allows custom methods to be added to
// CassandraClusterNamespaceLister.
type CassandraClusterNamespaceListerExpansion interface{}
