// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/vgkowski/cassandra-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CassandraClusters returns a CassandraClusterInformer.
	CassandraClusters() CassandraClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CassandraClusters returns a CassandraClusterInformer.
func (v *version) CassandraClusters() CassandraClusterInformer {
	return &cassandraClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
